"""
Portfolio Manager — final decision authority.

Synthesizes:
  - Research debate (bull vs bear → research judge recommendation)
  - Risk management debate (aggressive vs conservative vs neutral)
  - Past portfolio decisions (from BM25 memory)

Outputs a definitive 5-tier rating:
  BUY / OVERWEIGHT / HOLD / UNDERWEIGHT / SELL
"""
from __future__ import annotations

from .memory import get_memory


def get_portfolio_manager_prompt(
    symbol: str,
    trade_date: str,
    research_recommendation: str,
    risk_debate: str,
    reports: dict[str, str] | None = None,
) -> str:
    """Generate the portfolio manager's final decision prompt."""
    memory = get_memory("portfolio_manager")
    past_memories = memory.get_memories(
        f"{symbol} {research_recommendation[:200]}",
        n_matches=3,
    )

    memory_section = ""
    if past_memories:
        memory_section = "\n## Past Portfolio Decisions (from memory)\n"
        for m in past_memories:
            memory_section += f"\n**Situation**: {m['situation'][:150]}\n"
            memory_section += f"**Decision**: {m['recommendation'][:150]}\n"
            memory_section += f"**Outcome**: {m['outcome'][:100]}\n"

    return f"""You are the Chief Portfolio Manager at a leading quantitative hedge fund. You make the FINAL investment decision after reviewing all analyses and debates.

**Date**: {trade_date}
**Instrument**: {symbol}

## Research Team Recommendation
{research_recommendation}

## Risk Management Panel Debate
{risk_debate}
{memory_section}

## Your Decision Framework

You must deliver a DEFINITIVE rating and actionable plan. Consider:

1. **Evidence Quality**: How strong and consistent is the data across analysts?
2. **Risk-Reward**: Does the potential return justify the identified risks?
3. **Position Sizing**: Based on conviction level and risk tolerance
4. **Time Horizon**: When should this thesis play out?
5. **Risk Controls**: What triggers an exit?

## REQUIRED Output Format

**RATING**: [exactly one of: BUY / OVERWEIGHT / HOLD / UNDERWEIGHT / SELL]

**Executive Summary**:
A concise 2-3 sentence summary of the investment thesis and key rationale.

**Action Plan**:
- Entry Strategy: [immediate / scale-in / wait for pullback]
- Position Size: [% of portfolio]
- Time Horizon: [days / weeks / months]
- Stop Loss: [specific level or %]
- Take Profit: [specific target or %]

**Key Risks to Monitor**:
1. [risk 1]
2. [risk 2]
3. [risk 3]

**Conviction Level**: High / Medium / Low

IMPORTANT: Your RATING must be exactly one word from: BUY, OVERWEIGHT, HOLD, UNDERWEIGHT, SELL.
Ground every conclusion in specific evidence from the analyst reports and debates.
"""


# ── Signal Extraction ──────────────────────────────────────────────────────

def extract_signal(pm_response: str) -> str:
    """Extract the final rating from the portfolio manager's response.

    Returns one of: BUY, OVERWEIGHT, HOLD, UNDERWEIGHT, SELL
    """
    response_upper = pm_response.upper()

    # Look for explicit RATING line
    for line in response_upper.split("\n"):
        line = line.strip()
        if line.startswith("**RATING**") or line.startswith("RATING"):
            for rating in ["BUY", "OVERWEIGHT", "HOLD", "UNDERWEIGHT", "SELL"]:
                if rating in line:
                    return rating

    # Fallback: find the first occurrence of a rating word
    # Priority order (most decisive first)
    for rating in ["STRONG BUY", "BUY", "OVERWEIGHT", "STRONG SELL", "SELL", "UNDERWEIGHT", "HOLD"]:
        if rating in response_upper:
            # Normalize
            if rating == "STRONG BUY":
                return "BUY"
            if rating == "STRONG SELL":
                return "SELL"
            return rating

    return "HOLD"


# ── Decision Record ───────────────────────────────────────────────────────

def format_decision_record(
    symbol: str,
    trade_date: str,
    signal: str,
    pm_response: str,
    research_recommendation: str,
) -> str:
    """Format a complete decision record for storage and display."""
    return f"""# Trading Decision Record

**Date**: {trade_date}
**Symbol**: {symbol}
**Final Rating**: {signal}

## Portfolio Manager's Analysis
{pm_response}

## Research Team Recommendation
{research_recommendation}

---
*Decision generated by CheetahClaws Trading Agent*
"""
