"""research/lab/output.py — assemble the final markdown report.

We stitch together artifacts the orchestrator stashed in storage:
research questions, survey, outline, full body, citation verifications.
Output is a single Markdown file at
``~/.cheetahclaws/research_papers/<run_id>/report.md``.

Future: the same structure feeds Phase 2's LaTeX renderer; we keep
fields explicit (rq / survey / outline / body / refs) so a
``latex_writer.py`` can pick up without rewiring.
"""
from __future__ import annotations

import datetime as _dt
import json
import re
from pathlib import Path
from typing import Optional, TYPE_CHECKING

from .storage import DEFAULT_OUTPUT_DIR, LabStorage, human_dir_name

if TYPE_CHECKING:
    from .orchestrator import LabRun


def write_markdown_report(run: "LabRun", *,
                           output_dir: Optional[Path] = None) -> str:
    """Compose + persist the Markdown report; return the markdown text.

    All run artefacts (report.md, references.bib, citations_verified.json,
    sandbox workspace) live under the single ``run.output_dir`` so the
    user gets **one folder per /lab invocation**, named in the
    human-readable form ``<date>_<time>_<topic-slug>_<run_id_short>``.

    ``output_dir`` parameter is kept for back-compat — when given it
    overrides the per-run path entirely (used by tests that point at a
    tmp_path).
    """
    if output_dir is not None:
        # Explicit override (tests). Reproduce the human-name layout
        # underneath the override so tests still verify the naming.
        rec = run.storage.get_run(run.state.run_id)
        if rec is not None and getattr(rec, "created_at", None):
            run_dir = output_dir / human_dir_name(
                run.state.run_id, run.state.topic, rec.created_at
            )
        else:
            run_dir = output_dir / run.state.run_id
    else:
        run_dir = run.output_dir
    run_dir.mkdir(parents=True, exist_ok=True)

    md = _compose(run.state.run_id, run.state.topic, run.storage)
    (run_dir / "report.md").write_text(md, encoding="utf-8")

    # Bibliography also dumped separately so users can import into Zotero etc.
    bib = format_bibtex_from_storage(run.state.run_id, run.storage)
    if bib:
        (run_dir / "references.bib").write_text(bib, encoding="utf-8")

    # Verification log if present
    verif = run.storage.get_latest_artifact(run.state.run_id,
                                              "citations_verified")
    if verif:
        (run_dir / "citations_verified.json").write_text(
            verif.content, encoding="utf-8")

    return md


def _compose(run_id: str, topic: str, storage: LabStorage) -> str:
    rec = storage.get_run(run_id)
    rq_artifact = storage.get_latest_artifact(run_id, "rq")
    rq_decision = storage.get_latest_artifact(run_id, "rq_decision")
    survey      = storage.get_latest_artifact(run_id, "survey")
    outline     = storage.get_latest_artifact(run_id, "outline")
    results     = storage.get_latest_artifact(run_id, "results_section")
    draft       = storage.get_latest_artifact(run_id, "draft_full")
    verified    = storage.get_latest_artifact(run_id, "citations_verified")
    experiments = storage.list_experiments(run_id)

    today = _dt.date.today().isoformat()
    now_iso = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        f"# {_extract_title(draft.content if draft else '') or topic}",
        "",
        f"_Generated by cheetahclaws research lab on {today}._",
        "",
        f"**Topic:** {topic}",
    ]
    if rq_artifact:
        rqs = rq_artifact.content.strip()
        if rqs:
            lines += ["", "**Research questions:**", ""]
            for line in rqs.splitlines():
                lines.append(f"- {line.strip()}" if line.strip() else "")
            if rq_decision:
                lines += ["", f"_PI selection rationale:_ {rq_decision.content.strip()}"]

    lines += ["", "---", ""]

    if draft:
        lines.append(draft.content)
    elif outline:
        lines += ["## Outline (no full draft generated)", "",
                  outline.content]
    elif survey:
        lines += ["## Survey (no draft generated)", "", survey.content]

    # Experiment appendix (separate from Results — this is the raw record)
    if experiments:
        lines += ["", "---", "", "## Experiment log", ""]
        for e in experiments:
            ok_emoji = "✅" if (e.exit_code == 0 and not e.timed_out) else "❌"
            d = f"{e.duration_s:.2f}s" if e.duration_s else "—"
            lines.append(
                f"### Attempt {e.attempt} {ok_emoji}  exit={e.exit_code}  ·  {d}"
                + ("  ·  TIMED OUT" if e.timed_out else "")
            )
            lines.append("")
            lines.append("```python")
            lines.append((e.code or "")[:4000])
            lines.append("```")
            if e.stdout:
                lines += ["", "**stdout:**", "```", e.stdout[:2000], "```"]
            if e.stderr and e.exit_code != 0:
                lines += ["", "**stderr:**", "```", e.stderr[:1500], "```"]
            if e.artifacts:
                lines += ["", "**Artifacts:**"]
                for a in e.artifacts:
                    lines.append(f"  - `workspace/{a}`")
            lines.append("")

    # Verification appendix
    if verified:
        try:
            data = json.loads(verified.content)
        except Exception:
            data = []
        if data:
            lines += ["", "---", "", "## Citation verification report", ""]
            n_v = sum(1 for v in data if v.get("status") == "verified")
            n_a = sum(1 for v in data if v.get("status") == "ambiguous")
            n_n = sum(1 for v in data if v.get("status") == "not_found")
            n_s = sum(1 for v in data if v.get("status") == "verification_skipped")
            lines.append(
                f"_{n_v} verified · {n_a} ambiguous · {n_n} not found · "
                f"{n_s} skipped (network)._"
            )
            lines.append("")
            lines.append("| Status | Title (claimed) | Source | Notes |")
            lines.append("|---|---|---|---|")
            for v in data:
                status = v.get("status", "?")
                title = (v.get("title") or "")[:80].replace("|", "\\|")
                src = v.get("source") or "—"
                notes = (v.get("notes") or "")[:60].replace("|", "\\|")
                emoji = {"verified": "✅", "ambiguous": "⚠️",
                         "not_found": "❌",
                         "verification_skipped": "🔌"}.get(status, "?")
                lines.append(f"| {emoji} {status} | {title} | {src} | {notes} |")

    # Run metadata footer
    if rec:
        tok, cents = storage.get_budget(run_id)
        lines += ["", "---", "",
                  "<details><summary>Run metadata</summary>", "",
                  f"- **run_id**: `{rec.run_id}`",
                  f"- **status**: {rec.status}",
                  f"- **created_at**: {_dt.datetime.fromtimestamp(rec.created_at, _dt.timezone.utc).isoformat()}",
                  f"- **completed_at**: {_dt.datetime.fromtimestamp(rec.completed_at, _dt.timezone.utc).isoformat()}" if rec.completed_at else "- **completed_at**: pending",
                  f"- **tokens used**: {tok:,}",
                  f"- **cost (cents)**: {cents}",
                  f"- **report compiled**: {now_iso}",
                  "</details>"]
    return "\n".join(lines)


def _extract_title(body: str) -> str:
    """If the writer's draft starts with `# Title`, return that."""
    if not body:
        return ""
    for line in body.splitlines():
        line = line.strip()
        if line.startswith("# "):
            return line[2:].strip()
        if line:
            break
    return ""


# ── BibTeX dump ─────────────────────────────────────────────────────────


def format_bibtex_from_storage(run_id: str, storage: LabStorage) -> str:
    verif = storage.get_latest_artifact(run_id, "citations_verified")
    if not verif:
        return ""
    try:
        data = json.loads(verif.content)
    except Exception:
        return ""
    return format_bibtex(data)


def format_bibtex(verifications: list[dict]) -> str:
    """Render a basic bibtex bundle. Verified entries first, then notes
    on unverified.
    """
    out: list[str] = []
    for v in verifications:
        key = re.sub(r"\W+", "", (v.get("key") or "")) or "ref"
        title = v.get("matched_title") or v.get("title") or ""
        authors = v.get("matched_authors") or v.get("claimed_authors") or []
        url = v.get("matched_url") or ""
        status = v.get("status") or "?"
        if status == "not_found":
            out.append(f"% NOT FOUND — {title!r} (claimed authors: {authors})")
            continue
        out.append(f"@misc{{{key},")
        out.append(f"  title  = {{{title}}},")
        if authors:
            out.append(f"  author = {{{ ' and '.join(authors) }}},")
        if url:
            out.append(f"  url    = {{{url}}},")
        out.append(f"  note   = {{verification: {status}}},")
        out.append("}")
        out.append("")
    return "\n".join(out)
